<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\PostResponse;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getByUser(User $user, PostResponse $postResponse) {
        $query = $this->createQueryBuilder('ev')
            ->where('ev.user = :user')
            ->andWhere('ev.post_response = :postResponse')
            ->setParameter('postResponse', $postResponse)
            ->setParameter('user', $user)
            ->orderBy('ev.createdAt', 'ASC')
            ->getQuery();

        return $query->execute();
    }

}
