<?php

namespace AppBundle\Repository;

use AppBundle\Entity\EvaluationPost;
use AppBundle\Entity\User;
use AppBundle\Entity\Post;

/**
 * EvaluationPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationPostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUser(User $user, Post $post) {
        $query = $this->createQueryBuilder('ev')
            ->where('ev.user = :user')
            ->andWhere('ev.post = :post')
            ->setParameter('post', $post)
            ->setParameter('user', $user)
            ->orderBy('ev.createdAt', 'ASC')
            ->getQuery();

        return $query->execute();
    }

}
