<?php

namespace AppBundle\Repository;

/**
 * PostResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
