<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;

/**
 * PostResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostResponseRepository extends \Doctrine\ORM\EntityRepository
{

    public function getByPost(Post $post) {
        $query = $this->createQueryBuilder('pr')
            ->where('pr.post = :post')
            ->setParameter('post', $post)
            ->orderBy('pr.createdAt', 'ASC')
            ->getQuery();

        return $query->execute();
    }
}
