<?php

namespace AppBundle\Repository;

/**
 * QuizResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
